# Generated by Django 3.2 on 2022-10-18 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='accesskey',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
