# Generated by Django 3.2 on 2022-10-22 06:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_database_accesskey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200, unique=True)),
                ('original_id', models.IntegerField()),
                ('initial_label', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TemporalClaimSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal_content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='database',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='labeller_database_unique'),
        ),
        migrations.AddField(
            model_name='temporalclaimsection',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.claim'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.claim'),
        ),
        migrations.AddField(
            model_name='claim',
            name='database',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.database'),
        ),
        migrations.AddConstraint(
            model_name='temporalclaimsection',
            constraint=models.UniqueConstraint(fields=('claim', 'temporal_content'), name='labeller_temporal_claim_section_unique'),
        ),
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('claim', 'content'), name='labeller_evidence_unique'),
        ),
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('database', 'content'), name='labeller_claim_unique'),
        ),
    ]
