# Generated by Django 3.2 on 2022-10-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20221022_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='content',
            field=models.CharField(max_length=200),
        ),
    ]
