# Generated by Django 3.2 on 2022-10-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_claim_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='salt',
            field=models.CharField(default='hi', max_length=20),
            preserve_default=False,
        ),
    ]
