# Generated by Django 3.2 on 2022-10-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_database_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='salt',
        ),
        migrations.AlterField(
            model_name='database',
            name='accesskey',
            field=models.CharField(max_length=50),
        ),
    ]
