# Generated by Django 3.2 on 2022-10-29 03:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_auto_20221028_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator_email', models.CharField(max_length=100)),
                ('annotator_temporal_flag', models.BooleanField()),
                ('temporal_label', models.BooleanField()),
                ('general_label', models.BooleanField()),
                ('overall_label', models.BooleanField()),
                ('annotated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('manual_review_flag', models.BooleanField(default=False)),
                ('manual_review_comments', models.CharField(max_length=500)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.claim')),
            ],
        ),
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justification', models.CharField(max_length=100)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.annotation')),
            ],
        ),
        migrations.AddConstraint(
            model_name='justification',
            constraint=models.UniqueConstraint(fields=('annotation', 'justification'), name='justification_unique'),
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('claim', 'annotator_email'), name='annotation_unique'),
        ),
    ]
