# Generated by Django 3.2 on 2022-10-31 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20221029_0345'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='justification',
            name='justification_unique',
        ),
        migrations.AddField(
            model_name='justification',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.evidence'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='database.claim'),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='manual_review_comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='database.claim'),
        ),
    ]
