# Generated by Django 3.2 on 2022-11-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_auto_20221031_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='general_label',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='overall_label',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='annotation',
            name='temporal_label',
            field=models.CharField(max_length=30),
        ),
    ]
