# Generated by Django 3.2 on 2022-11-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_auto_20221101_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='type',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
