# Generated by Django 3.2 on 2022-11-01 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_justification_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='justification',
            old_name='type',
            new_name='temporal',
        ),
    ]
