# Generated by Django 3.2 on 2022-11-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_rename_type_justification_temporal'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='claim',
            name='labeller_claim_unique',
        ),
        migrations.AddField(
            model_name='claim',
            name='train_test_label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidence',
            name='initial_evidence_label',
            field=models.CharField(default='SUPPORTS', max_length=20),
            preserve_default=False,
        ),
    ]
