# Generated by Django 3.2 on 2022-11-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20221116_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='golden_evi',
            field=models.CharField(default='MIKE', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='train_test_label',
            field=models.IntegerField(),
        ),
    ]
