# Generated by Django 3.2 on 2022-11-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20221116_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='database.claim'),
        ),
    ]
