# Generated by Django 3.2 on 2022-11-17 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_alter_annotation_claim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='initial_evidence_label',
        ),
        migrations.AlterField(
            model_name='justification',
            name='annotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justifications', to='database.annotation'),
        ),
    ]
