# Generated by Django 3.2 on 2023-03-26 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20230124_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='annotator_temporal_flag',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='initial_label',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='train_test_label',
        ),
        migrations.RemoveField(
            model_name='database',
            name='is_temporal',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='golden_evi',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='title',
        ),
        migrations.AddField(
            model_name='evidence',
            name='original_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
