# Generated by Django 3.2 on 2023-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20230326_0501'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='claim',
            constraint=models.UniqueConstraint(fields=('database', 'content'), name='labeller_claim_unique'),
        ),
    ]
