# Generated by Django 3.2 on 2023-03-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_remove_evidence_original_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='annotation',
            name='annotation_unique',
        ),
        migrations.AddField(
            model_name='annotation',
            name='evidence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_annotations', to='database.evidence'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='annotation',
            constraint=models.UniqueConstraint(fields=('claim', 'evidence', 'annotator_email'), name='annotation_unique'),
        ),
    ]
