# Generated by Django 3.2 on 2023-03-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_auto_20230326_1918'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evidence',
            name='labeller_evidence_unique',
        ),
    ]
