# Generated by Django 3.2 on 2023-03-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_remove_evidence_labeller_evidence_unique'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(fields=('claim', 'content'), name='labeller_evidence_unique'),
        ),
    ]
