# Generated by Django 3.2 on 2023-03-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_evidence_labeller_evidence_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evidence',
            name='labeller_evidence_unique',
        ),
    ]
