# Generated by Django 3.2 on 2023-03-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0026_evidence_labeller_evidence_unique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annotation',
            old_name='manual_review_flag',
            new_name='ignore_flag',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='manual_review_comments',
        ),
        migrations.AddField(
            model_name='evidence',
            name='agreement_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='claim_temporal',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='evidence_temporal',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='final_label',
            field=models.CharField(choices=[('SUPPORTS', 'Supports'), ('REFUTES', 'Refutes'), ('NOT ENOUGH INFO', 'Not Enough Info')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='general_facts_justification',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='general_facts_label',
            field=models.CharField(choices=[('SUPPORTS', 'Supports'), ('REFUTES', 'Refutes'), ('NOT ENOUGH INFO', 'Not Enough Info')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='model_label',
            field=models.CharField(choices=[('SUPPORTS', 'Supports'), ('REFUTES', 'Refutes'), ('NOT ENOUGH INFO', 'Not Enough Info')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='relevant_evidence',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='same_entity_justification',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='same_entity_label',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='time_justification',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='time_label',
            field=models.CharField(choices=[('SUPPORTS', 'Supports'), ('REFUTES', 'Refutes'), ('NOT ENOUGH INFO', 'Not Enough Info')], default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='topic',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
