# Generated by Django 3.2 on 2023-04-04 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0029_auto_20230401_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotator_email', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('update_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
